### ISSUE TITLE
This solution freezes when I clone it with Wakanda studio 4 (production)

### ISSUE THREAD

**Issue by beebase** [Wakanda-Demos/School-Management#1]

**Comment by midrissi** [comment]
It was an authentication problem, and I have fixed it this morning ... Can you try now? and let me know if it works ;-)

**Comment by beebase** [comment]
Thanks, works now!

Sent from my iPhone

On 26 mrt. 2013, at 15:53, midrissi notifications@github.com wrote:

It was an authentication problem, and I have fixed it this morning ... Can
you try now? and let me know if it works ;-)

—
Reply to this email directly or view it on
GitHubhttps://github.com/Wakanda-Demos/School-Management/issues/1#issuecomment-15462807
.
